---

###
### Set a sane name for the rendered file
###
- name: register a sane template name
  set_fact:
    cloudformation_file_name: "{{ cloudformation.template | basename }}-{{ cloudformation.stack_name }}.yml"
  check_mode: False


###
### Render cloudformation jinja2 template into the build directory
###
- name: ensure cloudformation template is rendered
  template:
    src: "{{ cloudformation.template }}"
    dest: "{{ cloudformation_build_dir_path }}/{{ cloudformation_file_name }}"
    mode: 0644
    force: True
  changed_when: False
  check_mode: False


###
### Diff rendered cloudformation template (check mode only)
###
- name: diff cloudformation template parameters
  cloudformation_diff:
    ignore_hidden_params: True
    ignore_final_newline: False
    output_format: "{{ cloudformation_diff_output }}"
    output_choice: parameter
    stack_name: "{{ cloudformation.stack_name }}"
    template: "{{ cloudformation_build_dir_path }}/{{ cloudformation_file_name }}"
    template_tags: "{{ cloudformation.tags | default(omit) }}"
    template_parameters: "{{ cloudformation.template_parameters | default(omit) }}"
    aws_access_key: "{{ cloudformation.aws_access_key | default(cloudformation_defaults.aws_access_key | default(omit)) }}"
    aws_secret_key: "{{ cloudformation.aws_secret_key | default(cloudformation_defaults.aws_secret_key | default(omit)) }}"
    security_token: "{{ cloudformation.security_token | default(cloudformation_defaults.security_token | default(omit)) }}"
    profile: "{{ cloudformation.profile | default(cloudformation_defaults.profile | default(omit)) }}"
    region: "{{ cloudformation.region | default(cloudformation_defaults.region | default(omit)) }}"
  when: not cloudformation_generate_only and cloudformation_run_diff
  check_mode: False

- name: diff cloudformation template file
  cloudformation_diff:
    ignore_hidden_params: True
    ignore_final_newline: False
    output_format: "{{ cloudformation_diff_output }}"
    output_choice: template
    stack_name: "{{ cloudformation.stack_name }}"
    template: "{{ cloudformation_build_dir_path }}/{{ cloudformation_file_name }}"
    template_tags: "{{ cloudformation.tags | default(omit) }}"
    template_parameters: "{{ cloudformation.template_parameters | default(omit) }}"
    aws_access_key: "{{ cloudformation.aws_access_key | default(cloudformation_defaults.aws_access_key | default(omit)) }}"
    aws_secret_key: "{{ cloudformation.aws_secret_key | default(cloudformation_defaults.aws_secret_key | default(omit)) }}"
    security_token: "{{ cloudformation.security_token | default(cloudformation_defaults.security_token | default(omit)) }}"
    profile: "{{ cloudformation.profile | default(cloudformation_defaults.profile | default(omit)) }}"
    region: "{{ cloudformation.region | default(cloudformation_defaults.region | default(omit)) }}"
  when: not cloudformation_generate_only and cloudformation_run_diff
  check_mode: False


###
### Run rendered cloudformation template
###
- name: ensure cloudformation stack is present
  cloudformation:
    stack_name: "{{ cloudformation.stack_name }}"
    state: present
    template: "{{ cloudformation_build_dir_path }}/{{ cloudformation_file_name }}"

    aws_access_key: "{{ cloudformation.aws_access_key | default(cloudformation_defaults.aws_access_key | default(omit)) }}"
    aws_secret_key: "{{ cloudformation.aws_secret_key | default(cloudformation_defaults.aws_secret_key | default(omit)) }}"
    security_token: "{{ cloudformation.security_token | default(cloudformation_defaults.security_token | default(omit)) }}"
    profile: "{{ cloudformation.profile | default(cloudformation_defaults.profile | default(omit)) }}"
    region: "{{ cloudformation.region | default(cloudformation_defaults.region | default(omit)) }}"
    notification_arns: "{{ cloudformation.notification_arns | default(cloudformation_defaults.notification_arns | default(omit)) }}"
    template_parameters: "{{ cloudformation.template_parameters | default(omit) }}"
    tags: "{{ cloudformation.tags | default(omit) }}"
  when: not cloudformation_generate_only
